export const PRODUCTION_SCHEDULE_LOGICAL_KEY_COLUMNS = [
  'FSEIBAN',
  'FHINCD',
  'FSIGENCD',
  'FKOJUN',
] as const;

export const PRODUCTION_SCHEDULE_HASH_KEY_COLUMNS = [...PRODUCTION_SCHEDULE_LOGICAL_KEY_COLUMNS];

export const PRODUCTION_SCHEDULE_PRODUCT_NO_COLUMN = 'ProductNo';
