; Step C1: Avatar init() default (colorDepth=1). GitHub m5stack-avatar v0.8.2.

[platformio]
default_envs = m5stack-cores3-probe-stepc1

[env:m5stack-cores3-probe-stepc1]
platform = espressif32@6.3.2
board = esp32s3box
framework = arduino
board_build.arduino.memory_type = qio_qspi
board_build.arduino.partitions = ../cores3-probe/my_cores3_16MB.csv
monitor_filters = esp32_exception_decoder
board_build.f_flash = 80000000L
board_build.filesystem = spiffs
monitor_speed = 115200
upload_speed = 1500000
build_flags =
	-DBOARD_HAS_PSRAM
	-DARDUINO_M5STACK_CORES3
lib_deps =
	m5stack/M5Unified @ 0.2.7
	https://github.com/meganetaaan/m5stack-avatar.git#v0.8.2
lib_ldf_mode = deep
