import { listDueManagementGlobalRank, replaceDueManagementGlobalRank } from './due-management-global-rank.service.js';
import { buildDueManagementGlobalRankProposal } from './due-management-scoring.service.js';
import type { GlobalRankAutoGenerateResult, GlobalRankWritePolicy } from './due-management-scoring.types.js';
import { PRODUCTION_SCHEDULE_DASHBOARD_ID } from './constants.js';
import { prisma } from '../../lib/prisma.js';
import { dueManagementLearningEventRepository } from './due-management-learning-event.repository.js';

const defaultWritePolicy: GlobalRankWritePolicy = {
  minCandidateCount: 1,
  maxReorderDeltaRatio: 0.95,
  keepExistingTail: true
};

const normalizeFseibans = (items: string[]): string[] => {
  const seen = new Set<string>();
  const next: string[] = [];
  for (const item of items) {
    const normalized = item.trim();
    if (!normalized || seen.has(normalized)) continue;
    seen.add(normalized);
    next.push(normalized);
  }
  return next.slice(0, 2000);
};

const computeReorderDeltaRatio = (before: string[], after: string[]): number => {
  if (before.length === 0) return after.length > 0 ? 1 : 0;
  const beforeIndex = new Map(before.map((value, index) => [value, index]));
  let moved = 0;
  let compared = 0;
  for (let i = 0; i < after.length; i += 1) {
    const value = after[i];
    const prev = beforeIndex.get(value);
    if (prev === undefined) continue;
    compared += 1;
    if (prev !== i) moved += 1;
  }
  if (compared === 0) return 1;
  return moved / compared;
};

export async function autoGenerateDueManagementGlobalRank(params: {
  locationKey: string;
  writePolicy?: Partial<GlobalRankWritePolicy>;
  actorClientKey?: string | null;
}): Promise<GlobalRankAutoGenerateResult> {
  const policy: GlobalRankWritePolicy = {
    ...defaultWritePolicy,
    ...(params.writePolicy ?? {})
  };
  const previousOrderedFseibans = await listDueManagementGlobalRank(params.locationKey);
  const dueConfiguredRows = await prisma.productionScheduleSeibanDueDate.findMany({
    where: {
      csvDashboardId: PRODUCTION_SCHEDULE_DASHBOARD_ID,
      location: params.locationKey,
      fseiban: { in: previousOrderedFseibans }
    },
    select: { fseiban: true }
  });
  const dueConfiguredSet = new Set(dueConfiguredRows.map((row) => row.fseiban));
  const sanitizedPreviousOrderedFseibans = previousOrderedFseibans.filter((fseiban) => dueConfiguredSet.has(fseiban));
  const proposal = await buildDueManagementGlobalRankProposal({ locationKey: params.locationKey });
  const selectedRows = await prisma.productionScheduleTriageSelection.findMany({
    where: {
      csvDashboardId: PRODUCTION_SCHEDULE_DASHBOARD_ID,
      location: params.locationKey
    },
    orderBy: [{ selectedAt: 'asc' }, { fseiban: 'asc' }],
    select: { fseiban: true }
  });
  await dueManagementLearningEventRepository.saveProposalEvent({
    locationKey: params.locationKey,
    proposal,
    selectedFseibans: selectedRows.map((row) => row.fseiban),
    writePolicy: policy as unknown as Record<string, unknown>,
    actorClientKey: params.actorClientKey ?? null
  });
  if (proposal.candidateCount < policy.minCandidateCount) {
    await dueManagementLearningEventRepository.saveDecisionEvent({
      locationKey: params.locationKey,
      sourceType: 'auto',
      orderedFseibans: sanitizedPreviousOrderedFseibans,
      previousOrderedFseibans: sanitizedPreviousOrderedFseibans,
      proposalOrderedFseibans: proposal.orderedFseibans,
      reorderDeltaRatio: 0,
      metadata: {
        applied: false,
        guardReason: `candidate_count_below_minimum(${proposal.candidateCount} < ${policy.minCandidateCount})`
      }
    });
    return {
      success: true,
      applied: false,
      orderedFseibans: sanitizedPreviousOrderedFseibans,
      previousOrderedFseibans: sanitizedPreviousOrderedFseibans,
      sourceType: 'auto',
      guard: {
        rejected: true,
        reason: `candidate_count_below_minimum(${proposal.candidateCount} < ${policy.minCandidateCount})`,
        reorderDeltaRatio: 0
      },
      proposal
    };
  }

  const keptTail = policy.keepExistingTail
    ? sanitizedPreviousOrderedFseibans.filter((fseiban) => !proposal.orderedFseibans.includes(fseiban))
    : [];
  const nextOrderedFseibans = normalizeFseibans([...proposal.orderedFseibans, ...keptTail]);
  const reorderDeltaRatio = computeReorderDeltaRatio(sanitizedPreviousOrderedFseibans, nextOrderedFseibans);
  if (reorderDeltaRatio > policy.maxReorderDeltaRatio) {
    await dueManagementLearningEventRepository.saveDecisionEvent({
      locationKey: params.locationKey,
      sourceType: 'auto',
      orderedFseibans: sanitizedPreviousOrderedFseibans,
      previousOrderedFseibans: sanitizedPreviousOrderedFseibans,
      proposalOrderedFseibans: proposal.orderedFseibans,
      reorderDeltaRatio,
      metadata: {
        applied: false,
        guardReason: `reorder_delta_ratio_exceeded(${reorderDeltaRatio.toFixed(3)} > ${policy.maxReorderDeltaRatio.toFixed(3)})`
      }
    });
    return {
      success: true,
      applied: false,
      orderedFseibans: sanitizedPreviousOrderedFseibans,
      previousOrderedFseibans: sanitizedPreviousOrderedFseibans,
      sourceType: 'auto',
      guard: {
        rejected: true,
        reason: `reorder_delta_ratio_exceeded(${reorderDeltaRatio.toFixed(3)} > ${policy.maxReorderDeltaRatio.toFixed(3)})`,
        reorderDeltaRatio
      },
      proposal
    };
  }

  const orderedFseibans = await replaceDueManagementGlobalRank({
    locationKey: params.locationKey,
    orderedFseibans: nextOrderedFseibans,
    sourceType: 'auto'
  });
  await dueManagementLearningEventRepository.saveDecisionEvent({
    locationKey: params.locationKey,
    sourceType: 'auto',
    orderedFseibans,
    previousOrderedFseibans: sanitizedPreviousOrderedFseibans,
    proposalOrderedFseibans: proposal.orderedFseibans,
    reorderDeltaRatio,
    metadata: {
      applied: true
    }
  });

  return {
    success: true,
    applied: true,
    orderedFseibans,
    previousOrderedFseibans: sanitizedPreviousOrderedFseibans,
    sourceType: 'auto',
    guard: {
      rejected: false,
      reason: null,
      reorderDeltaRatio
    },
    proposal: {
      ...proposal,
      orderedFseibans
    }
  };
}
