import Fastify from 'fastify';
import jwt from 'jsonwebtoken';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  verify: vi.fn(), command: vi.fn(), selection: vi.fn(), dailyPlan: vi.fn(),
  rank: vi.fn(), auto: vi.fn(), importHours: vi.fn(), proposal: vi.fn(), learning: vi.fn()
}));
vi.mock('../../../../config/env.js', () => ({ env: { JWT_ACCESS_SECRET: 'test-due-management-secret' } }));
vi.mock('../../../../services/production-schedule/production-schedule-settings.service.js', () => ({
  SHARED_DUE_MANAGEMENT_PASSWORD_LOCATION: 'shared', verifyDueManagementAccessPassword: mocks.verify
}));
vi.mock('../../../../services/production-schedule/due-management-command.service.js', () => ({
  upsertProductionScheduleDueManagementPartProcessingType: mocks.command,
  upsertProductionScheduleDueManagementPartNote: mocks.command,
  upsertProductionSchedulePartPriorities: mocks.command,
  upsertProductionScheduleSeibanDueDate: mocks.command,
  upsertProductionScheduleSeibanProcessingDueDate: mocks.command
}));
vi.mock('../../../../services/production-schedule/due-management-location-scope-adapter.service.js', () => ({
  toDueManagementScopeFromContext: (context: unknown) => context,
  resolveDueManagementStorageLocationKey: (scope: { deviceScopeKey: string }) => scope.deviceScopeKey
}));
vi.mock('../../../../services/production-schedule/due-management-selection.service.js', () => ({
  getDueManagementTriageSelections: vi.fn(async () => []), replaceDueManagementTriageSelections: mocks.selection
}));
vi.mock('../../../../services/production-schedule/due-management-daily-plan.service.js', () => ({
  getDueManagementDailyPlan: vi.fn(), replaceDueManagementDailyPlan: mocks.dailyPlan
}));
vi.mock('../../../../services/production-schedule/due-management-resource-filter.service.js', () => ({
  hasDueManagementResourceFilter: vi.fn(() => false), listDueManagementFilteredFseibans: vi.fn()
}));
vi.mock('../../../../services/production-schedule/due-management-triage.service.js', () => ({ listDueManagementTriage: vi.fn() }));
vi.mock('../../../../services/production-schedule/production-schedule-search-state.service.js', () => ({ getProductionScheduleSearchState: vi.fn() }));
vi.mock('../../../../services/production-schedule/due-management-global-rank.service.js', () => ({
  listDueManagementGlobalRank: vi.fn(async () => []), replaceDueManagementGlobalRank: mocks.rank
}));
vi.mock('../../../../services/production-schedule/due-management-global-rank-auto.service.js', () => ({ autoGenerateDueManagementGlobalRank: mocks.auto }));
vi.mock('../../../../services/production-schedule/due-management-scoring.service.js', () => ({ buildDueManagementGlobalRankProposal: mocks.proposal }));
vi.mock('../../../../services/production-schedule/due-management-scoring-explainer.service.js', () => ({ explainGlobalRankProposalItem: vi.fn() }));
vi.mock('../../../../services/production-schedule/due-management-learning-evaluator.service.js', () => ({ evaluateDueManagementLearningReport: vi.fn() }));
vi.mock('../../../../services/production-schedule/due-management-learning-event.repository.js', () => ({
  dueManagementLearningEventRepository: { saveProposalEvent: mocks.learning, saveDecisionEvent: mocks.learning }
}));
vi.mock('../../../../services/production-schedule/actual-hours/actual-hours-import-orchestrator.service.js', () => ({
  ActualHoursImportOrchestratorService: class { importAndRebuild = mocks.importHours; }
}));
vi.mock('../../../../services/production-schedule/production-actual-hours-aggregate.service.js', () => ({
  ProductionActualHoursAggregateService: class { getStats = vi.fn(); }
}));
vi.mock('../../shared.js', () => ({ shouldRequireTargetLocationForActor: (actor: { canProxyOtherDevices: boolean }) => actor.canProxyOtherDevices }));

import { authenticate, signDueManagementToken } from '../../../../lib/auth.js';
import { ApiError } from '../../../../lib/errors.js';
import { registerProductionScheduleDueManagementAuthRoute } from '../due-management-auth.js';
import { registerProductionScheduleDueManagementProcessingRoute } from '../due-management-processing.js';
import { registerProductionScheduleDueManagementNoteRoute } from '../due-management-note.js';
import { registerProductionScheduleDueManagementPartPrioritiesRoute } from '../due-management-part-priorities.js';
import { registerProductionScheduleDueManagementTriageRoute } from '../due-management-triage.js';
import { registerProductionScheduleDueManagementGlobalRankRoute } from '../due-management-global-rank.js';
import { registerProductionScheduleDueManagementActualHoursRoute } from '../due-management-actual-hours.js';
import { registerProductionScheduleDueManagementDueDateRoute } from '../due-management-due-date.js';
import { registerProductionScheduleDueManagementProcessingDueDateRoute } from '../due-management-processing-due-date.js';
import type { KioskRouteDeps } from '../shared.js';

const base = '/kiosk/production-schedule/due-management';
const routes = [
  { method: 'PUT', path: '/seiban/A/parts/X/processing', payload: { processingType: '塗装' }, service: mocks.command },
  { method: 'PUT', path: '/seiban/A/parts/X/note', payload: { note: 'memo' }, service: mocks.command },
  { method: 'PUT', path: '/seiban/A/part-priorities', payload: { orderedFhincds: ['X'] }, service: mocks.command },
  { method: 'PUT', path: '/triage/selection', payload: { selectedFseibans: ['A'] }, service: mocks.selection },
  { method: 'PUT', path: '/daily-plan', payload: { orderedFseibans: ['A'] }, service: mocks.dailyPlan },
  { method: 'PUT', path: '/global-rank', payload: { orderedFseibans: ['A'] }, service: mocks.rank },
  { method: 'PUT', path: '/global-rank/auto-generate', payload: {}, service: mocks.auto },
  { method: 'POST', path: '/actual-hours/import', payload: { csvContent: 'csv' }, service: mocks.importHours }
] as const;
const secret = 'test-due-management-secret';
let app: ReturnType<typeof Fastify>;

beforeEach(async () => {
  vi.clearAllMocks();
  mocks.verify.mockResolvedValue({ success: true });
  mocks.command.mockResolvedValue({ success: true });
  mocks.selection.mockResolvedValue(['A']);
  mocks.dailyPlan.mockResolvedValue({ orderedFseibans: ['A'], items: [] });
  mocks.rank.mockResolvedValue(['A']);
  mocks.auto.mockResolvedValue({ success: true });
  mocks.importHours.mockResolvedValue({ imported: 1 });
  mocks.proposal.mockResolvedValue({ orderedFseibans: ['A'] });
  app = Fastify();
  app.setErrorHandler((error, _request, reply) => {
    void reply.code(error instanceof ApiError ? error.statusCode : 500).send({ code: (error as ApiError).code });
  });
  const deps: KioskRouteDeps = {
    requireClientDevice: async (key) => ({ clientKey: String(key), clientDevice: { id: String(key), name: 'terminal' } }),
    resolveLocationScopeContext: () => ({ deviceScopeKey: 'actor-location', siteKey: 'site', canProxyOtherDevices: false }) as ReturnType<KioskRouteDeps['resolveLocationScopeContext']>,
    resolveTargetLocation: ({ requestedTargetLocation, actorLocation }) => requestedTargetLocation ?? actorLocation,
    leaderboardShellSnapshotStore: {} as KioskRouteDeps['leaderboardShellSnapshotStore']
  };
  for (const register of [registerProductionScheduleDueManagementAuthRoute, registerProductionScheduleDueManagementProcessingRoute,
    registerProductionScheduleDueManagementNoteRoute, registerProductionScheduleDueManagementPartPrioritiesRoute,
    registerProductionScheduleDueManagementTriageRoute, registerProductionScheduleDueManagementGlobalRankRoute,
    registerProductionScheduleDueManagementActualHoursRoute, registerProductionScheduleDueManagementDueDateRoute,
    registerProductionScheduleDueManagementProcessingDueDateRoute]) await register(app, deps);
  app.get('/user', { preHandler: authenticate }, async (request) => request.user);
});
afterEach(async () => { await app.close(); });

describe('due-management authorization', () => {
  it.each(routes)('requires a valid device token for $path', async ({ method, path, payload, service }) => {
    const cases = [
      [undefined, 'DUE_MANAGEMENT_TOKEN_REQUIRED'],
      ['invalid', 'DUE_MANAGEMENT_TOKEN_INVALID'],
      [signDueManagementToken('other-device'), 'DUE_MANAGEMENT_TOKEN_DEVICE_MISMATCH'],
      [jwt.sign({ purpose: 'due-management', clientDeviceId: 'device' }, secret, { expiresIn: -1 }), 'DUE_MANAGEMENT_TOKEN_EXPIRED'],
      [jwt.sign({ sub: 'user', username: 'test', role: 'ADMIN' }, secret, { expiresIn: '1h' }), 'DUE_MANAGEMENT_TOKEN_INVALID'],
      [jwt.sign({ purpose: 'other', clientDeviceId: 'device' }, secret, { expiresIn: '1h' }), 'DUE_MANAGEMENT_TOKEN_INVALID'],
      [jwt.sign({ purpose: 'due-management', clientDeviceId: 'device' }, secret), 'DUE_MANAGEMENT_TOKEN_INVALID'],
      [jwt.sign({ purpose: 'due-management', clientDeviceId: 'device' }, 'different-test-secret', { expiresIn: '1h' }), 'DUE_MANAGEMENT_TOKEN_INVALID']
    ];
    for (const [token, code] of cases) {
      const response = await app.inject({ method, url: base + path, payload,
        headers: { 'x-client-key': 'device', ...(token ? { 'x-due-management-token': token } : {}) } });
      expect(response.statusCode).toBe(403);
      expect(response.json().code).toBe(code);
      expect(service).not.toHaveBeenCalled();
    }
    const response = await app.inject({ method, url: base + path, payload,
      headers: { 'x-client-key': 'device', 'x-due-management-token': signDueManagementToken('device') } });
    expect(response.statusCode).toBe(200);
    expect(service).toHaveBeenCalledOnce();
  });

  it.each(['/seiban/A/due-date', '/seiban/A/processing/LSLH/due-date'])('keeps %s available without a token', async (path) => {
    const response = await app.inject({ method: 'PUT', url: base + path, headers: { 'x-client-key': 'device' }, payload: { dueDate: '2026-10-07' } });
    expect(response.statusCode).toBe(200);
    expect(mocks.command).toHaveBeenCalledOnce();
  });

  it('issues a device token for twelve hours only after password confirmation', async () => {
    const request = { method: 'POST' as const, url: base + '/verify-access-password', headers: { 'x-client-key': 'device' }, payload: { password: 'test-password' } };
    const response = await app.inject(request);
    expect(response.statusCode).toBe(200);
    const token = response.json().token as string;
    const claims = jwt.verify(token, secret) as jwt.JwtPayload;
    expect(claims).toMatchObject({ purpose: 'due-management', clientDeviceId: 'device' });
    expect(claims.exp! - claims.iat!).toBe(12 * 60 * 60);
    expect(claims).not.toHaveProperty('sub');
    expect(claims).not.toHaveProperty('role');
    const update = await app.inject({ method: 'PUT', url: base + '/seiban/A/parts/X/note', payload: { note: 'memo' }, headers: { 'x-client-key': 'device', 'x-due-management-token': token } });
    expect(update.statusCode).toBe(200);
    mocks.verify.mockResolvedValue({ success: false });
    const rejected = await app.inject(request);
    expect(rejected.json()).toEqual({ success: false });
  });

  it('separates due-management and user authentication', async () => {
    const dueResponse = await app.inject({ url: '/user', headers: { authorization: `Bearer ${signDueManagementToken('device')}` } });
    expect(dueResponse.statusCode).toBe(401);
    expect(dueResponse.json().code).toBe('AUTH_TOKEN_INVALID');
    const userToken = jwt.sign({ sub: 'user', username: 'test', role: 'ADMIN' }, secret, { expiresIn: '1h' });
    const userResponse = await app.inject({ url: '/user', headers: { authorization: `Bearer ${userToken}` } });
    expect(userResponse.statusCode).toBe(200);
    expect(userResponse.json()).toEqual({ id: 'user', username: 'test', role: 'ADMIN' });
  });

  it('binds proxy operations to the actor device independently of the target location', async () => {
    await app.close();
    app = Fastify();
    app.setErrorHandler((error, _request, reply) => { void reply.code((error as ApiError).statusCode).send({ code: (error as ApiError).code }); });
    await registerProductionScheduleDueManagementGlobalRankRoute(app, {
      requireClientDevice: async () => ({ clientKey: 'actor-key', clientDevice: { id: 'actor-device', name: 'Mac' } }),
      resolveLocationScopeContext: () => ({ deviceScopeKey: 'actor-location', siteKey: 'site', canProxyOtherDevices: true }) as ReturnType<KioskRouteDeps['resolveLocationScopeContext']>,
      resolveTargetLocation: ({ requestedTargetLocation }) => requestedTargetLocation!,
      leaderboardShellSnapshotStore: {} as KioskRouteDeps['leaderboardShellSnapshotStore']
    });
    for (const targetLocation of ['target-a', 'target-b']) {
      const response = await app.inject({ method: 'PUT', url: base + '/global-rank/auto-generate', payload: { targetLocation }, headers: { 'x-client-key': 'actor-key', 'x-due-management-token': signDueManagementToken('actor-device') } });
      expect(response.statusCode).toBe(200);
      expect(mocks.auto).toHaveBeenLastCalledWith(expect.objectContaining({ targetLocationScope: expect.objectContaining({ deviceScopeKey: targetLocation }) }));
    }
    const response = await app.inject({ method: 'PUT', url: base + '/global-rank/auto-generate', payload: { targetLocation: 'target-a' }, headers: { 'x-client-key': 'actor-key', 'x-due-management-token': signDueManagementToken('target-a') } });
    expect(response.statusCode).toBe(403);
    expect(response.json().code).toBe('DUE_MANAGEMENT_TOKEN_DEVICE_MISMATCH');
  });
});
