/**
 * 順位ボード資源カード（サイネージ JPEG）のグリッド定数。
 * 5列×2段・1ページ最大10資源カード（各カード幅は列数増で自動的に狭くなる）。
 */
export const LEADER_ORDER_SIGNAGE_GRID_COLUMNS = 5;
export const LEADER_ORDER_SIGNAGE_GRID_ROWS = 2;

export const LEADER_ORDER_SIGNAGE_GRID_CAPACITY =
  LEADER_ORDER_SIGNAGE_GRID_COLUMNS * LEADER_ORDER_SIGNAGE_GRID_ROWS;

export const DEFAULT_LEADER_ORDER_CARDS_PER_PAGE = LEADER_ORDER_SIGNAGE_GRID_CAPACITY;
export const MAX_LEADER_ORDER_CARDS_PER_PAGE = LEADER_ORDER_SIGNAGE_GRID_CAPACITY;
