/**
 * 順位ボード資源カード（サイネージ JPEG）のグリッド定数。
 * 進捗一覧（4列×2段）と同型で、1ページ最大8資源カード。
 */
export const LEADER_ORDER_SIGNAGE_GRID_COLUMNS = 4;
export const LEADER_ORDER_SIGNAGE_GRID_ROWS = 2;

export const LEADER_ORDER_SIGNAGE_GRID_CAPACITY =
  LEADER_ORDER_SIGNAGE_GRID_COLUMNS * LEADER_ORDER_SIGNAGE_GRID_ROWS;

export const DEFAULT_LEADER_ORDER_CARDS_PER_PAGE = LEADER_ORDER_SIGNAGE_GRID_CAPACITY;
export const MAX_LEADER_ORDER_CARDS_PER_PAGE = LEADER_ORDER_SIGNAGE_GRID_CAPACITY;
