export {
  LOAN_INSPECTION_ACTIVE_BAND_WARNING_MIX as MI_LOAN_ACTIVE_BAND_WARNING_MIX,
  LOAN_INSPECTION_BODY_FIRST_LINE_LEADIN_YPX as MI_BODY_FIRST_LINE_LEADIN_YPX,
  LOAN_INSPECTION_CARD_BOTTOM_PAD_PX as MI_CARD_BOTTOM_PAD_PX,
  LOAN_INSPECTION_CARD_CORNER_RADIUS_PX as MI_CARD_CORNER_RADIUS_PX,
  LOAN_INSPECTION_CARD_INNER_PAD_PX as MI_CARD_INNER_PAD_PX,
  LOAN_INSPECTION_HEADER_BAND_END_YPX as MI_HEADER_BAND_END_YPX,
  LOAN_INSPECTION_HEADER_TO_BODY_GAP_YPX as MI_HEADER_TO_BODY_GAP_YPX,
  LOAN_INSPECTION_NAME_HEADER_BASELINE_YPX as MI_NAME_HEADER_BASELINE_YPX,
  LOAN_INSPECTION_NAMES_START_YPX as MI_NAMES_START_YPX,
  getHeaderBodyGapCssPixels,
  scaleDesignPx,
} from '../../shared/loan-inspection-card/card-metrics.js';
