import type { FastifyInstance } from 'fastify';

import { autoGenerateDueManagementGlobalRank } from '../../../services/production-schedule/due-management-global-rank-auto.service.js';
import {
  listDueManagementGlobalRank,
  replaceDueManagementGlobalRank
} from '../../../services/production-schedule/due-management-global-rank.service.js';
import { explainGlobalRankProposalItem } from '../../../services/production-schedule/due-management-scoring-explainer.service.js';
import { buildDueManagementGlobalRankProposal } from '../../../services/production-schedule/due-management-scoring.service.js';
import {
  productionScheduleDueManagementGlobalRankAutoGenerateBodySchema,
  productionScheduleDueManagementGlobalRankBodySchema,
  productionScheduleDueManagementGlobalRankExplanationParamsSchema,
  type KioskRouteDeps
} from './shared.js';

export async function registerProductionScheduleDueManagementGlobalRankRoute(
  app: FastifyInstance,
  deps: KioskRouteDeps
): Promise<void> {
  app.get('/kiosk/production-schedule/due-management/global-rank', { config: { rateLimit: false } }, async (request) => {
    const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
    const locationKey = deps.resolveLocationKey(clientDevice);
    const orderedFseibans = await listDueManagementGlobalRank(locationKey);
    return {
      orderedFseibans
    };
  });

  app.put('/kiosk/production-schedule/due-management/global-rank', { config: { rateLimit: false } }, async (request) => {
    const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
    const locationKey = deps.resolveLocationKey(clientDevice);
    const body = productionScheduleDueManagementGlobalRankBodySchema.parse(request.body);
    const orderedFseibans = await replaceDueManagementGlobalRank({
      locationKey,
      orderedFseibans: body.orderedFseibans
    });
    return {
      success: true,
      orderedFseibans
    };
  });

  app.get(
    '/kiosk/production-schedule/due-management/global-rank/proposal',
    { config: { rateLimit: false } },
    async (request) => {
      const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
      const locationKey = deps.resolveLocationKey(clientDevice);
      const proposal = await buildDueManagementGlobalRankProposal({ locationKey });
      return proposal;
    }
  );

  app.put(
    '/kiosk/production-schedule/due-management/global-rank/auto-generate',
    { config: { rateLimit: false } },
    async (request) => {
      const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
      const locationKey = deps.resolveLocationKey(clientDevice);
      const writePolicy = productionScheduleDueManagementGlobalRankAutoGenerateBodySchema.parse(request.body);
      const result = await autoGenerateDueManagementGlobalRank({
        locationKey,
        writePolicy
      });
      return result;
    }
  );

  app.get(
    '/kiosk/production-schedule/due-management/global-rank/explanation/:fseiban',
    { config: { rateLimit: false } },
    async (request) => {
      const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
      const locationKey = deps.resolveLocationKey(clientDevice);
      const params = productionScheduleDueManagementGlobalRankExplanationParamsSchema.parse(request.params);
      const proposal = await buildDueManagementGlobalRankProposal({ locationKey });
      const item = explainGlobalRankProposalItem(proposal, params.fseiban);
      return {
        fseiban: params.fseiban,
        found: Boolean(item),
        item
      };
    }
  );
}
