import type { FastifyInstance } from 'fastify';

import { ApiError } from '../../../lib/errors.js';
import { autoGenerateDueManagementGlobalRank } from '../../../services/production-schedule/due-management-global-rank-auto.service.js';
import { dueManagementLearningEventRepository } from '../../../services/production-schedule/due-management-learning-event.repository.js';
import { resolveRankingScopePolicy } from '../../../services/production-schedule/due-management-ranking-scope-policy.service.js';
import { evaluateDueManagementLearningReport } from '../../../services/production-schedule/due-management-learning-evaluator.service.js';
import {
  listDueManagementGlobalRank,
  replaceDueManagementGlobalRank
} from '../../../services/production-schedule/due-management-global-rank.service.js';
import { getDueManagementTriageSelections } from '../../../services/production-schedule/due-management-selection.service.js';
import { explainGlobalRankProposalItem } from '../../../services/production-schedule/due-management-scoring-explainer.service.js';
import { buildDueManagementGlobalRankProposal } from '../../../services/production-schedule/due-management-scoring.service.js';
import {
  productionScheduleDueManagementGlobalRankAutoGenerateBodySchema,
  productionScheduleDueManagementGlobalRankBodySchema,
  productionScheduleDueManagementGlobalRankExplanationParamsSchema,
  productionScheduleDueManagementGlobalRankQuerySchema,
  productionScheduleDueManagementLearningReportQuerySchema,
  type KioskRouteDeps
} from './shared.js';
import { shouldRequireTargetLocationForActor } from '../shared.js';

const requireTargetLocationIfNeeded = (params: {
  actorLocation: string;
  requestedTargetLocation?: string;
}): void => {
  if (!shouldRequireTargetLocationForActor(params.actorLocation)) {
    return;
  }
  if (params.requestedTargetLocation && params.requestedTargetLocation.trim().length > 0) {
    return;
  }
  throw new ApiError(
    400,
    'Mac端末では操作対象ロケーション(targetLocation)の指定が必要です',
    undefined,
    'TARGET_LOCATION_REQUIRED'
  );
};

export async function registerProductionScheduleDueManagementGlobalRankRoute(
  app: FastifyInstance,
  deps: KioskRouteDeps
): Promise<void> {
  app.get('/kiosk/production-schedule/due-management/global-rank', { config: { rateLimit: false } }, async (request) => {
    const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
    const locationScopeContext = deps.resolveLocationScopeContext(clientDevice);
    const actorLocation = locationScopeContext.deviceScopeKey;
    const query = productionScheduleDueManagementGlobalRankQuerySchema.parse(request.query);
    requireTargetLocationIfNeeded({ actorLocation, requestedTargetLocation: query.targetLocation });
    const targetLocation = deps.resolveTargetLocation({
      requestedTargetLocation: query.targetLocation,
      actorLocation
    });
    const scopePolicy = resolveRankingScopePolicy({
      requestedScope: query.rankingScope,
      actorLocation,
      targetLocation
    });
    const orderedFseibans = await listDueManagementGlobalRank({
      locationKey: scopePolicy.rankLocationKey,
      targetLocation: scopePolicy.targetLocation,
      scope: scopePolicy.scope
    });
    return {
      orderedFseibans,
      targetLocation: scopePolicy.targetLocation,
      actorLocation,
      rankingScope: scopePolicy.scope
    };
  });

  app.put('/kiosk/production-schedule/due-management/global-rank', { config: { rateLimit: false } }, async (request) => {
    const { clientDevice, clientKey } = await deps.requireClientDevice(request.headers['x-client-key']);
    const locationScopeContext = deps.resolveLocationScopeContext(clientDevice);
    const actorLocation = locationScopeContext.deviceScopeKey;
    const body = productionScheduleDueManagementGlobalRankBodySchema.parse(request.body);
    requireTargetLocationIfNeeded({ actorLocation, requestedTargetLocation: body.targetLocation });
    const targetLocation = deps.resolveTargetLocation({
      requestedTargetLocation: body.targetLocation,
      actorLocation
    });
    const scopePolicy = resolveRankingScopePolicy({
      requestedScope: body.rankingScope,
      actorLocation,
      targetLocation
    });
    const previousOrderedFseibans = await listDueManagementGlobalRank({
      locationKey: scopePolicy.rankLocationKey,
      targetLocation: scopePolicy.targetLocation,
      scope: scopePolicy.scope
    });
    const [proposal, selectedFseibans] = await Promise.all([
      buildDueManagementGlobalRankProposal({
        locationKey: scopePolicy.targetLocation,
        locationScope: { deviceScopeKey: scopePolicy.targetLocation },
        existingRankLocationKey: scopePolicy.rankLocationKey
      }),
      getDueManagementTriageSelections(scopePolicy.targetLocation)
    ]);
    await dueManagementLearningEventRepository.saveProposalEvent({
      locationKey: scopePolicy.targetLocation,
      proposal,
      selectedFseibans,
      writePolicy: null,
      actorClientKey: clientKey
    });
    const orderedFseibans = await replaceDueManagementGlobalRank({
      locationKey: scopePolicy.rankLocationKey,
      targetLocation: scopePolicy.targetLocation,
      scope: scopePolicy.scope,
      actorClientKey: clientKey,
      orderedFseibans: body.orderedFseibans,
      sourceType: 'manual'
    });
    await dueManagementLearningEventRepository.saveDecisionEvent({
      locationKey: scopePolicy.targetLocation,
      sourceType: 'manual',
      reasonCode: body.reasonCode ?? null,
      orderedFseibans,
      previousOrderedFseibans,
      proposalOrderedFseibans: proposal.orderedFseibans,
      reorderDeltaRatio: null,
      metadata: {
        from: 'global_rank_manual_put',
        reasonCode: body.reasonCode ?? null,
        actorClientKey: clientKey,
        actorLocation,
        targetLocation: scopePolicy.targetLocation,
        scope: scopePolicy.scope
      }
    });
    return {
      success: true,
      orderedFseibans,
      targetLocation: scopePolicy.targetLocation,
      actorLocation,
      rankingScope: scopePolicy.scope
    };
  });

  app.get(
    '/kiosk/production-schedule/due-management/global-rank/proposal',
    { config: { rateLimit: false } },
    async (request) => {
      const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
      const locationScopeContext = deps.resolveLocationScopeContext(clientDevice);
      const actorLocation = locationScopeContext.deviceScopeKey;
      const query = productionScheduleDueManagementGlobalRankQuerySchema.parse(request.query);
      requireTargetLocationIfNeeded({ actorLocation, requestedTargetLocation: query.targetLocation });
      const targetLocation = deps.resolveTargetLocation({
        requestedTargetLocation: query.targetLocation,
        actorLocation
      });
      const scopePolicy = resolveRankingScopePolicy({
        requestedScope: query.rankingScope,
        actorLocation,
        targetLocation
      });
      const proposal = await buildDueManagementGlobalRankProposal({
        locationKey: scopePolicy.targetLocation,
        locationScope: { deviceScopeKey: scopePolicy.targetLocation },
        existingRankLocationKey: scopePolicy.rankLocationKey
      });
      return proposal;
    }
  );

  app.put(
    '/kiosk/production-schedule/due-management/global-rank/auto-generate',
    { config: { rateLimit: false } },
    async (request) => {
      const { clientDevice, clientKey } = await deps.requireClientDevice(request.headers['x-client-key']);
      const locationScopeContext = deps.resolveLocationScopeContext(clientDevice);
      const actorLocation = locationScopeContext.deviceScopeKey;
      const writePolicy = productionScheduleDueManagementGlobalRankAutoGenerateBodySchema.parse(request.body);
      requireTargetLocationIfNeeded({ actorLocation, requestedTargetLocation: writePolicy?.targetLocation });
      const targetLocation = deps.resolveTargetLocation({
        requestedTargetLocation: writePolicy?.targetLocation,
        actorLocation
      });
      const result = await autoGenerateDueManagementGlobalRank({
        locationKey: actorLocation,
        targetLocation,
        scope: writePolicy?.rankingScope,
        writePolicy,
        actorClientKey: clientKey
      });
      return result;
    }
  );

  app.get(
    '/kiosk/production-schedule/due-management/global-rank/learning-report',
    { config: { rateLimit: false } },
    async (request) => {
      const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
      const locationScopeContext = deps.resolveLocationScopeContext(clientDevice);
      const actorLocation = locationScopeContext.deviceScopeKey;
      const query = productionScheduleDueManagementLearningReportQuerySchema.parse(request.query);
      requireTargetLocationIfNeeded({ actorLocation, requestedTargetLocation: query.targetLocation });
      const targetLocation = deps.resolveTargetLocation({
        requestedTargetLocation: query.targetLocation,
        actorLocation
      });
      const scopePolicy = resolveRankingScopePolicy({
        requestedScope: query.rankingScope,
        actorLocation,
        targetLocation
      });
      const report = await evaluateDueManagementLearningReport({
        locationKey: scopePolicy.targetLocation,
        locationScope: { deviceScopeKey: scopePolicy.targetLocation },
        from: query.from,
        to: query.to
      });
      return report;
    }
  );

  app.get(
    '/kiosk/production-schedule/due-management/global-rank/explanation/:fseiban',
    { config: { rateLimit: false } },
    async (request) => {
      const { clientDevice } = await deps.requireClientDevice(request.headers['x-client-key']);
      const locationScopeContext = deps.resolveLocationScopeContext(clientDevice);
      const actorLocation = locationScopeContext.deviceScopeKey;
      const query = productionScheduleDueManagementGlobalRankQuerySchema.parse(request.query);
      requireTargetLocationIfNeeded({ actorLocation, requestedTargetLocation: query.targetLocation });
      const targetLocation = deps.resolveTargetLocation({
        requestedTargetLocation: query.targetLocation,
        actorLocation
      });
      const scopePolicy = resolveRankingScopePolicy({
        requestedScope: query.rankingScope,
        actorLocation,
        targetLocation
      });
      const params = productionScheduleDueManagementGlobalRankExplanationParamsSchema.parse(request.params);
      const proposal = await buildDueManagementGlobalRankProposal({
        locationKey: scopePolicy.targetLocation,
        locationScope: { deviceScopeKey: scopePolicy.targetLocation },
        existingRankLocationKey: scopePolicy.rankLocationKey
      });
      const item = explainGlobalRankProposalItem(proposal, params.fseiban);
      return {
        fseiban: params.fseiban,
        found: Boolean(item),
        item
      };
    }
  );
}
