---
- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: restart security monitor
  ansible.builtin.systemd:
    name: security-monitor.timer
    state: restarted
    enabled: true

- name: reload ssh
  ansible.builtin.systemd:
    name: ssh
    state: reloaded

- name: restart wayvnc
  ansible.builtin.systemd:
    name: wayvnc
    state: restarted
